apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-api
  namespace: project-testing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sapura
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 50
          type: Utilization