apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sapura-hpa
  namespace: project-testing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sapura-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
